#!/bin/bash                                                                                                                                    
gcc -Wall -Werror -Wextra -pedantic -std=gnu89  -c main.c > main.o
